### PR TITLE
Removed the fixed a.href and img.src

### PR DESCRIPTION
**Pull request by nexeck**
Changed the Fixed a.href and img.src Tags to

HTML::image
HTML::anchor
HTML::style
HTML::script

### CODE REVIEW

**Comment by nexeck** [comment]
Startet git Integration Guide for Windows.
How to use SSH Key with PHPStorm

**Comment by goyote** [comment]
Nice work! Mentioning git and github was on my todo list! I'll merge this today. I have a question about the usage of the HTML class, is is really necessary? that is, do you see a benefit? Considering that the assets directory is not part of any route, it statically sits in ROOT/assets/ ... ? And that most likely will never change.

**Comment by goyote** [comment]
Ok, I guess the confusion is the assets directory is in the modules directory, so there must be a route for it. but for the moment being, im just copy pasting the module/assets dir into the root/assets directory. This should be resolved soon since I'm planning on using a new module for that.

**Comment by goyote** [comment]
I created a "github" and "git" section and added your stuff there, thanks for the help. I'll come up with an easier way to fork the project and get it up and running locally.

**Comment by nexeck** [comment]
I am using the HTML Class, because my base URL is not "/"
its something like "XYZ/kohana-project/public/"

**Pull request closed without merging**
